# Generated by Django 4.1.7 on 2023-04-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('ci', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=8)),
                ('correo', models.EmailField(max_length=210)),
                ('productos', models.CharField(max_length=200)),
            ],
        ),
    ]
