# Generated by Django 4.1.7 on 2023-05-28 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('numero_de_factura', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Número')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('fecha', models.DateField(verbose_name='Fecha')), 
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('ci', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=8)),
                ('correo', models.EmailField(max_length=210)),
                ('descripcion', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('cantidad_productos', models.PositiveIntegerField(verbose_name='Cantidad de productos')),
                ('categoria', models.CharField(choices=[('bebida', 'Bebida'), ('sandwich', 'Sandwich'), ('pasta', 'Pasta'), ('carne', 'Carne'), ('dulce', 'Dulce'), ('golosina', 'Golosina')], default='1', max_length=10, verbose_name='Categoría')),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='cafeteria_app.proveedor', verbose_name='Proveedor')),
            ],
        ),
    ]
