# Generated by Django 4.1.7 on 2023-05-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.CharField(max_length=50, verbose_name='Precio'),
        ),
    ]
