# Generated by Django 4.1.7 on 2023-06-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria_app', '0004_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('bebida', 'Bebida'), ('sandwich', 'Sandwich'), ('pasta', 'Pasta'), ('carne', 'Carne'), ('dulce', 'Dulce'), ('golosina', 'Golosina'), ('aseo', 'Aseo')], default='bebida', max_length=10, verbose_name='Categoría'),
        ),
    ]
